// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctiarwswjjjucaldwhyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0aWFyd3N3ampqdWNhbGR3aHlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTQ4NjMsImV4cCI6MjA2OTg5MDg2M30.DuJbCtF7EUndYN-0_IHaxcgnsswGPx-k_65gc3mknqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});